# -*- coding: utf-8 -*-
"""Pertemuan 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzpxkNGgFdvrqQZCNYyPKq0BVbrDxNvl

**Membuat Array**
"""

import array as arr
a = arr.array('i', [1, 2, 3])
print('Array yang baru dibuat adalah: ', end=" ")
for i in range(0, 3):
  print(a[i], end=" ")
print()
b = arr.array('d', [1.5, 2.5, 3.5])
print('Array yang baru dibuat adalah: ', end=" ")
for i in range(0, 3):
  print(b[i], end=" ")
print()

"""**Menambahkan Elemen Array**"""

import array as arr
a = arr.array('i', [1, 2, 3])
print('Array sebelum ditambahkan elemen: ', end=" ")
for i in range(0, 3):
  print(a[i], end=" ")
print()
a.insert(1, 4)
print('Array setelah ditambahkan elemen: ', end=" ")
for i in (a):
  print(i, end=" ")
print()
b = arr.array('d', [1.5, 2.5, 3.5])
print('Array sebelum ditambahkan elemen: ', end=" ")
for i in range(0, 3):
  print(b[i], end=" ")
print()
b.append(4.5)
print('Array setelah ditambahkan elemen: ', end=" ")
for i in (b):
  print(i, end=" ")
print()

"""**Mengakses Elemen Array**"""

import array as arr
a = arr.array('i', [1, 2, 3, 4, 5, 6])
print('Akses elemen array: ', a[0])
print('Akses elemen array: ', a[5])
b = arr.array('d', [1.5, 2.5, 3.5, 4.5, 5.5, 6.6])
print('Akses elemen array: ', b[0])
print('Akses elemen array: ', b[5])

"""**Menghapus Elemen Array**"""

import array
arr = array.array('i', [1, 2, 3, 2, 3])
print('Array yang baru dibuat adalah: ', end=" ")
for i in range(0, 5):
  print(arr[i], end=" ")
print()

print("\r")
print('Elemen yang dihapus: ', end= " ")
print(arr.pop(2))
print("Array setelah elemen dihapus: ", end=" ")
for i in range(0, 4):
  print(arr[i], end=" ")
print()

print("\r")
arr.remove(1)
print("Array setelah elemen dihapus: ", end=" ")
for i in range(0, 3):
  print(arr[i], end=" ")
print()

"""**Pemotongan Elemen Array**"""

import array as arr
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = arr.array("i", l)
print("Array utuh: ")
for i in (a):
  print(i, end=" ")
array_potong = a[2:4]
print("\nPotong elemen pada jangkauan 2-4: ")
print(array_potong)
array_potong = a[3:]
print("\nElemen terpotong kulai dari array 3 sampai akhir: ")
print(array_potong)
array_potong = a[:]
print("\nMemotong semua elemen array: ")
print(array_potong)

"""**Mengubah Elemen Array**"""

import array
arr = array.array('i', [1, 2, 3, 3, 2, 1])
print('Array sebelum diperbarui: ', end=' ')
for i in range(0, 6):
  print(arr[i], end=" ")
print()

print("\r")
arr[2] = 6
print('Array setelah diperbarui: ', end=' ')
for i in range(0, 6):
  print(arr[i], end=" ")
print()
arr[4] = 8
print('Array setelah diperbarui: ', end=' ')
for i in range(0, 6):
  print(arr[i], end=" ")
print()

"""**Berbagai Operasi Array**"""

import array
my_array = array.array('i', [1, 2, 3, 4, 3, 2, 5])

# Menghitung elemen array
count = my_array.count(5)
print("Jumlah angka array ini adalah: ", count)

# Membalik elemen array
print("Array asli", *my_array)
my_array.reverse()
print("Array dibalik", *my_array)

"""**Extend dalam Array**"""

import array as arr
a = arr.array('i', [1, 2, 3, 4, 5])
print("Array sebelum diperluas: ", end=" ")
for i in range(0, 5):
  print(a[i], end=" ")
print()
a.extend([6, 7, 8, 9, 10])
print("\nArray setelah diperluas: ", end=" ")
for i in range(0, 10):
  print(a[i], end=" ")
print()

import array as arr
a = arr.array('i', [1, 2, 3, 4, 5, 6])
print("Array sebelum diperluas: ", end=" ")
for i in range(0, 6):
  print(a[i], end=" ")
print()
a.extend([7, 8, 9, 10, 11, 12])
print("\nArray setelah diperluas: ", end=" ")

for i in range(0, 12):
  print(a[i], end=" ")
print()

b = arr.array('d', [1.5, 2.5, 3.5, 4.5, 5.5, 6.6])
print("\nArray sebelum diperluas: ", end=" ")
for i in range(0, 6):
  print(b[i], end=" ")
print()
b.extend([7.5, 8.5, 9.5, 10.5, 11.5, 12.5])
print("\nArray setelah diperluas: ", end=" ")
for i in range(0, 9+1):
  print(b[i], end=" ")
print()

